<!--NAVIGATION-->

<a href="https://colab.research.google.com/github/bpesquet/machine-learning-katas/blob/master/notebooks/katas/workflow/PreprocessingFunctions.ipynb"><img align="left" src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open in Colab" title="Open in Google Colaboratory"></a>


## Instructions

This is a self-correcting exercise generated by [nbgrader](https://github.com/jupyter/nbgrader). 

Fill in any place that says `YOUR CODE HERE` or `YOUR ANSWER HERE`. Run subsequent cells to check your code.

---

# Kata: Code Preprocessing Functions From Scratch

## Package setup

In [12]:
import numpy as np

## Training/test set splitting

### Question

Complete the following function to split `data` between training and test sets, according to the `test_size` ratio.

In [14]:
def train_test_split(data, test_size):
    x_train = data[:round(data.shape[0]*(1-test_size)),:]
    x_test = data[:round(data.shape[0]*(test_size)),:]
    return x_train, x_test
x = np.random.rand(30, 3)
print(x.shape)
x_train, x_test = train_test_split(x, .25)
print(f'x_train: {x_train.shape}. x_test: {x_test.shape}')

(30, 3)
22
x_train: (22, 3). x_test: (8, 3)


In [15]:
# Generate a random (30,3) tensor
x = np.random.rand(30, 3)

x_train, x_test = train_test_split(x, .25)
print(f'x_train: {x_train.shape}. x_test: {x_test.shape}')

assert x_train.shape == (22,3)
assert x_test.shape == (8,3)

22
x_train: (22, 3). x_test: (8, 3)


In [ ]:
# Generate a random (30,3) tensor
x = np.random.rand(30, 3)

x_train, x_test = train_test_split(x, .33)
print(f'x_train: {x_train.shape}. x_test: {x_test.shape}')

assert x_train.shape == (20,3)
assert x_test.shape == (10,3)

## Feature scaling

### Question

Complete the following function to implement min-max feature scaling.

In [50]:
def scale_min_max(data):
    return (data - data.min())/(data.max()-data.min())
x = np.random.randint(1, 10, (3,3))
print(x.std())

2.4241582476968255


In [26]:
# Generate a random (3,3) tensor with values between 1 and 10
x = np.random.randint(1, 10, (3,3))

x_scaled = scale_min_max(x)
print(x_scaled)

assert x_scaled.min() == 0
assert x_scaled.max() == 1

[[0.    0.875 0.75 ]
 [0.5   0.875 0.375]
 [0.75  1.    0.75 ]]


### Question

Complete the following function to implement feature scaling by standardization.

In [51]:
def scale_standard(data, mean=None, std=None):
    if mean == None:
        mean = data.mean()
    if std == None:
        std = data.std()
    return (data - mean)/std

In [52]:
# Generate a random (3,3) tensor with values between 1 and 10
x = np.random.randint(1, 10, (3,3))

x_scaled = scale_standard(x)
print(x_scaled)

mean_scaled = x_scaled.mean()
std_scaled = x_scaled.std()
print(f'Mean: {mean_scaled}. Std: {std_scaled}')

assert np.abs(np.max(mean_scaled)) < 10**-6
assert np.abs(np.max(std_scaled - 1)) < 10**-6

[[-1.56804866 -0.25526374  1.05752119]
 [-0.9116562   1.05752119  1.05752119]
 [ 1.05752119 -0.58345997 -0.9116562 ]]
Mean: -1.2335811384723961e-17. Std: 1.0


### Question

Use the previous function to scale `x_train` and `x_test` while preventing information leakage from the test set.

In [54]:
x_train_scaled, x_test_scaled = train_test_split(x_scaled, .25)

2


## Feature encoding

### Question

Complete the following function to one-hot encode a class vector (integers) into a matrix of binary vectors.

In [107]:
def one_hot_encode(elements):
    result = np.zeros((len(elements), elements.max()+1))
    row = np.arange(len(elements))
    result[row,elements] = 1
    return result


In [108]:
x = np.array([0, 5, 3])

x_hot = one_hot_encode(x)
print(x_hot)

assert np.array_equal(x_hot[0], [1, 0, 0, 0, 0, 0])
assert np.array_equal(x_hot[1], [0, 0, 0, 0, 0, 1])
assert np.array_equal(x_hot[2], [0, 0, 0, 1, 0, 0])

[[1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]]


In [109]:
x = np.array([3, 2, 1, 4, 2, 3])

x_hot = one_hot_encode(x)
print(x_hot)

assert np.array_equal(x_hot[0], [0, 0, 0, 1, 0])
assert np.array_equal(x_hot[1], [0, 0, 1, 0, 0])
assert np.array_equal(x_hot[2], [0, 1, 0, 0, 0])
assert np.array_equal(x_hot[3], [0, 0, 0, 0, 1])
assert np.array_equal(x_hot[4], [0, 0, 1, 0, 0])
assert np.array_equal(x_hot[5], [0, 0, 0, 1, 0])

[[0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]
